basePath: /api/v1
definitions:
  inputs.NewProject:
    properties:
      title:
        type: string
    type: object
  model.Health:
    properties:
      connectedToDb:
        type: boolean
    type: object
  model.Project:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
info:
  contact:
    email: email@ded.fr
    name: API Support
  description: API to manage projects
  license: {}
  title: Tezos Link API
  version: v1
paths:
  /health:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Health'
      summary: get application health
  /projects:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Project'
      summary: Get all Projects
    post:
      parameters:
      - description: New Project
        in: body
        name: new-project
        required: true
        schema:
          $ref: '#/definitions/inputs.NewProject'
          type: object
      produces:
      - application/json
      responses:
        "201": {}
        "400": {}
      summary: Create a Project
  /projects/{id}:
    get:
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Project'
      summary: Get a Project
swagger: "2.0"
