version: '2.1'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: tezoslink
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
  backend:
    build:
      context: .
      dockerfile: build/package/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      ENV: local
    links:
      - postgres
    depends_on:
      - postgres
