name: Deploy
on:
  push:
    branches-ignore:
      - 'master'  

jobs:

  build:
    name: Test and build
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        make deps
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      run: make build
    
    - name: Setup docker
      uses: docker-practice/actions-setup-docker@0.0.1
    
    - name: Unit test
      run: make unit-test
      
    - name: Integration test
      run: make integration-test
      
    - name: Build
      run: make build-unix
