name: CI/CD Front

on:
  push:
    paths:
    - 'web/**'
    - '.github/workflows/deploy_front.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Install dependancies
      run: make deps

    - name: Build frontend
      run: make build-frontend

    - name: Upload artifact (only on master)
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: web/build
  
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Install AWS cli
      uses: chrislennon/action-aws-cli@1.1

    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Deploy frontend
      run: aws s3 sync ./build s3://tezoslink-front
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
