name: Deploy
on:
  push:
    branches:
      - master

jobs:

  build-deploy:
    name: Test, build and deploy
    runs-on: ubuntu-18.04
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        make deps
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      run: make build
    
    - name: Setup docker
      uses: docker-practice/actions-setup-docker@0.0.1
    
    - name: Unit test
      run: make unit-test
      
    - name: Build
      run: make build-unix

    - name: Build docker images
      run: make docker-images

    - name: Tag docker images
      run: make docker-tag

    - name: Push docker images to registry
      run: make docker-push
      
    - name: Build frontend
      run: make build-frontend
      
    - name: Install AWS cli
      uses: chrislennon/action-aws-cli@1.1
      
    - name: Deploy frontend
      run: make deploy-frontend
    
    - name: Deploy lambda
      run: make deploy-lambda
